version: "3"
services:
  sentiments-analyzer:
    build:
      context:  ../../sentiments-analyzer
    image: stefanpapp/sentiments-analyzer

  entity-detector:
      build:
        context:  ../../entity-detector
      image: stefanpapp/entity-detector
