apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: stefanpapp/udacity-restapi-feed
        name: backend-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: URL
        - name: AWS_MEDIA_BUCKET
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_MEDIA_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: JWT_SECRET
        - name: POSTGRESS_DATABASE
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: POSTGRESS_DATABASE
        - name: POSTGRESS_HOST
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: POSTGRESS_HOST
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: POSTGRESS_PASSWORD
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: POSTGRESS_USERNAME
