apiVersion: v1
kind: Service
metadata:
  labels:
    service: entity-detector
  name: entity-detector
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: entity-detector
