apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: entity-detector
  name: entity-detector
spec:
  replicas: 2
  selector:
    matchLabels:
      service: entity-detector
  template:
    metadata:
      labels:
        service: entity-detector
    spec:
      containers:
      - image: stefanpapp/entity-detector
        name: entity-detector
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
          - name: ARN
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: ARN
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_ACCESS_KEY
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_SECRET_KEY
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_REGION
          - name: LANDING_ZONE
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: LANDING_ZONE
          - name: COMPLETE_ZONE
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: COMPLETE_ZONE
      restartPolicy: Always
