apiVersion: v1
kind: Service
metadata:
  labels:
    service: sentiment-analyzer
  name: sentiment-analyzer
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: sentiment-analyzer
