apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: text-analyzer
  name: text-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      service: text-analyzer
  template:
    metadata:
      labels:
        service: text-analyzer
    spec:
      containers:
      - image: stefanpapp/text-analyzer
        name: text-analyzer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
