apiVersion: v1
kind: Service
metadata:
  labels:
    service: text-analyzer
  name: text-analyzer
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: text-analyzer
